/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FeatureCard: typeof import('./pages/home/components/Features/FeatureCard.vue')['default']
    Features: typeof import('./pages/home/components/Features/index.vue')['default']
    Hero: typeof import('./pages/home/components/hero/Hero.vue')['default']
    LocaleToggler: typeof import('./components/blocks/LocaleToggler.vue')['default']
    Logo: typeof import('./components/blocks/Logo.vue')['default']
    RentalFrequency: typeof import('./pages/dashboard/overview/components/RentalFrequency.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./components/blocks/Settings.vue')['default']
    StatCardOverview: typeof import('./pages/dashboard/overview/components/StatCardOverview.vue')['default']
    ThemeToggler: typeof import('./components/blocks/ThemeToggler.vue')['default']
    ToggleDirection: typeof import('./components/blocks/ToggleDirection.vue')['default']
  }
}
